# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DomeGUI.ui'
#
# Created: Tue Jul 23 14:45:02 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_DomeGUI(object):
    def setupUi(self, DomeGUI):
        DomeGUI.setObjectName(_fromUtf8("DomeGUI"))
        DomeGUI.resize(876, 871)
        self.centralwidget = QtGui.QWidget(DomeGUI)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.glWidget = GLWidget(self.centralwidget)
        self.glWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.glWidget.setObjectName(_fromUtf8("glWidget"))
        self.horizontalLayout.addWidget(self.glWidget)
        DomeGUI.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(DomeGUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 876, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        DomeGUI.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(DomeGUI)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        DomeGUI.setStatusBar(self.statusbar)
        self.dockNavigation = QtGui.QDockWidget(DomeGUI)
        self.dockNavigation.setObjectName(_fromUtf8("dockNavigation"))
        self.grpSettings = QtGui.QWidget()
        self.grpSettings.setObjectName(_fromUtf8("grpSettings"))
        self.formLayout_3 = QtGui.QFormLayout(self.grpSettings)
        self.formLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.grpGeneral = QtGui.QGroupBox(self.grpSettings)
        self.grpGeneral.setObjectName(_fromUtf8("grpGeneral"))
        self.verticalLayout = QtGui.QVBoxLayout(self.grpGeneral)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.chkShowProjectorImages = QtGui.QCheckBox(self.grpGeneral)
        self.chkShowProjectorImages.setObjectName(_fromUtf8("chkShowProjectorImages"))
        self.verticalLayout.addWidget(self.chkShowProjectorImages)
        self.chkEdgeBlending = QtGui.QCheckBox(self.grpGeneral)
        self.chkEdgeBlending.setObjectName(_fromUtf8("chkEdgeBlending"))
        self.verticalLayout.addWidget(self.chkEdgeBlending)
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.grpGeneral)
        self.grpDome = QtGui.QGroupBox(self.grpSettings)
        self.grpDome.setObjectName(_fromUtf8("grpDome"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.grpDome)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lbDomeDiameter = QtGui.QLabel(self.grpDome)
        self.lbDomeDiameter.setObjectName(_fromUtf8("lbDomeDiameter"))
        self.verticalLayout_2.addWidget(self.lbDomeDiameter)
        self.boxDomeDiameter = QtGui.QDoubleSpinBox(self.grpDome)
        self.boxDomeDiameter.setProperty("value", 15.0)
        self.boxDomeDiameter.setObjectName(_fromUtf8("boxDomeDiameter"))
        self.verticalLayout_2.addWidget(self.boxDomeDiameter)
        self.lbBaseHeight = QtGui.QLabel(self.grpDome)
        self.lbBaseHeight.setObjectName(_fromUtf8("lbBaseHeight"))
        self.verticalLayout_2.addWidget(self.lbBaseHeight)
        self.boxBaseHeight = QtGui.QDoubleSpinBox(self.grpDome)
        self.boxBaseHeight.setProperty("value", 3.5)
        self.boxBaseHeight.setObjectName(_fromUtf8("boxBaseHeight"))
        self.verticalLayout_2.addWidget(self.boxBaseHeight)
        self.lbTowerHeight = QtGui.QLabel(self.grpDome)
        self.lbTowerHeight.setObjectName(_fromUtf8("lbTowerHeight"))
        self.verticalLayout_2.addWidget(self.lbTowerHeight)
        self.boxTowerHeight = QtGui.QDoubleSpinBox(self.grpDome)
        self.boxTowerHeight.setProperty("value", 3.5)
        self.boxTowerHeight.setObjectName(_fromUtf8("boxTowerHeight"))
        self.verticalLayout_2.addWidget(self.boxTowerHeight)
        self.chkShowDome = QtGui.QCheckBox(self.grpDome)
        self.chkShowDome.setChecked(True)
        self.chkShowDome.setObjectName(_fromUtf8("chkShowDome"))
        self.verticalLayout_2.addWidget(self.chkShowDome)
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.grpDome)
        self.grpProjectorSettings = QtGui.QGroupBox(self.grpSettings)
        self.grpProjectorSettings.setObjectName(_fromUtf8("grpProjectorSettings"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.grpProjectorSettings)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.lbAngleOfView = QtGui.QLabel(self.grpProjectorSettings)
        self.lbAngleOfView.setObjectName(_fromUtf8("lbAngleOfView"))
        self.verticalLayout_3.addWidget(self.lbAngleOfView)
        self.boxAngleOfView = QtGui.QDoubleSpinBox(self.grpProjectorSettings)
        self.boxAngleOfView.setMaximum(360.0)
        self.boxAngleOfView.setProperty("value", 120.0)
        self.boxAngleOfView.setObjectName(_fromUtf8("boxAngleOfView"))
        self.verticalLayout_3.addWidget(self.boxAngleOfView)
        self.lbAspectRatio = QtGui.QLabel(self.grpProjectorSettings)
        self.lbAspectRatio.setObjectName(_fromUtf8("lbAspectRatio"))
        self.verticalLayout_3.addWidget(self.lbAspectRatio)
        self.boxAspectRatio = QtGui.QDoubleSpinBox(self.grpProjectorSettings)
        self.boxAspectRatio.setMinimum(0.0)
        self.boxAspectRatio.setMaximum(1.0)
        self.boxAspectRatio.setSingleStep(0.01)
        self.boxAspectRatio.setProperty("value", 0.75)
        self.boxAspectRatio.setObjectName(_fromUtf8("boxAspectRatio"))
        self.verticalLayout_3.addWidget(self.boxAspectRatio)
        self.chkShowProjectors = QtGui.QCheckBox(self.grpProjectorSettings)
        self.chkShowProjectors.setChecked(True)
        self.chkShowProjectors.setObjectName(_fromUtf8("chkShowProjectors"))
        self.verticalLayout_3.addWidget(self.chkShowProjectors)
        self.chkShowScreenPoints = QtGui.QCheckBox(self.grpProjectorSettings)
        self.chkShowScreenPoints.setChecked(True)
        self.chkShowScreenPoints.setObjectName(_fromUtf8("chkShowScreenPoints"))
        self.verticalLayout_3.addWidget(self.chkShowScreenPoints)
        self.chkProjectedPoints = QtGui.QCheckBox(self.grpProjectorSettings)
        self.chkProjectedPoints.setChecked(True)
        self.chkProjectedPoints.setObjectName(_fromUtf8("chkProjectedPoints"))
        self.verticalLayout_3.addWidget(self.chkProjectedPoints)
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.grpProjectorSettings)
        self.grpProjectorPositioning = QtGui.QGroupBox(self.grpSettings)
        self.grpProjectorPositioning.setObjectName(_fromUtf8("grpProjectorPositioning"))
        self.gridLayout = QtGui.QGridLayout(self.grpProjectorPositioning)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalGroupBox = QtGui.QGroupBox(self.grpProjectorPositioning)
        self.horizontalGroupBox.setObjectName(_fromUtf8("horizontalGroupBox"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalGroupBox)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lbOffset = QtGui.QLabel(self.horizontalGroupBox)
        self.lbOffset.setObjectName(_fromUtf8("lbOffset"))
        self.horizontalLayout_3.addWidget(self.lbOffset)
        self.boxOffsetX = QtGui.QDoubleSpinBox(self.horizontalGroupBox)
        self.boxOffsetX.setMinimum(-20.0)
        self.boxOffsetX.setMaximum(20.0)
        self.boxOffsetX.setSingleStep(0.1)
        self.boxOffsetX.setObjectName(_fromUtf8("boxOffsetX"))
        self.horizontalLayout_3.addWidget(self.boxOffsetX)
        self.boxOffsetY = QtGui.QDoubleSpinBox(self.horizontalGroupBox)
        self.boxOffsetY.setMinimum(-20.0)
        self.boxOffsetY.setMaximum(20.0)
        self.boxOffsetY.setSingleStep(0.1)
        self.boxOffsetY.setObjectName(_fromUtf8("boxOffsetY"))
        self.horizontalLayout_3.addWidget(self.boxOffsetY)
        self.boxOffsetZ = QtGui.QDoubleSpinBox(self.horizontalGroupBox)
        self.boxOffsetZ.setMinimum(-20.0)
        self.boxOffsetZ.setMaximum(20.0)
        self.boxOffsetZ.setSingleStep(0.1)
        self.boxOffsetZ.setObjectName(_fromUtf8("boxOffsetZ"))
        self.horizontalLayout_3.addWidget(self.boxOffsetZ)
        self.gridLayout.addWidget(self.horizontalGroupBox, 4, 0, 1, 1)
        self.grpPitchAngle = QtGui.QHBoxLayout()
        self.grpPitchAngle.setObjectName(_fromUtf8("grpPitchAngle"))
        self.lbPitchAngle = QtGui.QLabel(self.grpProjectorPositioning)
        self.lbPitchAngle.setObjectName(_fromUtf8("lbPitchAngle"))
        self.grpPitchAngle.addWidget(self.lbPitchAngle)
        self.boxPitchAngle = QtGui.QDoubleSpinBox(self.grpProjectorPositioning)
        self.boxPitchAngle.setMaximum(360.0)
        self.boxPitchAngle.setSingleStep(1.0)
        self.boxPitchAngle.setProperty("value", 45.0)
        self.boxPitchAngle.setObjectName(_fromUtf8("boxPitchAngle"))
        self.grpPitchAngle.addWidget(self.boxPitchAngle)
        self.gridLayout.addLayout(self.grpPitchAngle, 2, 0, 1, 1)
        self.grpYawAngle = QtGui.QHBoxLayout()
        self.grpYawAngle.setObjectName(_fromUtf8("grpYawAngle"))
        self.lbYawAngle = QtGui.QLabel(self.grpProjectorPositioning)
        self.lbYawAngle.setObjectName(_fromUtf8("lbYawAngle"))
        self.grpYawAngle.addWidget(self.lbYawAngle)
        self.boxYawAngle = QtGui.QDoubleSpinBox(self.grpProjectorPositioning)
        self.boxYawAngle.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.boxYawAngle.setMaximum(360.0)
        self.boxYawAngle.setObjectName(_fromUtf8("boxYawAngle"))
        self.grpYawAngle.addWidget(self.boxYawAngle)
        self.gridLayout.addLayout(self.grpYawAngle, 1, 0, 1, 1)
        self.horizontalWidget = QtGui.QWidget(self.grpProjectorPositioning)
        self.horizontalWidget.setObjectName(_fromUtf8("horizontalWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lbProjector = QtGui.QLabel(self.horizontalWidget)
        self.lbProjector.setObjectName(_fromUtf8("lbProjector"))
        self.horizontalLayout_2.addWidget(self.lbProjector)
        self.btnProj1 = QtGui.QRadioButton(self.horizontalWidget)
        self.btnProj1.setChecked(True)
        self.btnProj1.setObjectName(_fromUtf8("btnProj1"))
        self.horizontalLayout_2.addWidget(self.btnProj1)
        self.btnProj2 = QtGui.QRadioButton(self.horizontalWidget)
        self.btnProj2.setChecked(False)
        self.btnProj2.setObjectName(_fromUtf8("btnProj2"))
        self.horizontalLayout_2.addWidget(self.btnProj2)
        self.btnProj3 = QtGui.QRadioButton(self.horizontalWidget)
        self.btnProj3.setObjectName(_fromUtf8("btnProj3"))
        self.horizontalLayout_2.addWidget(self.btnProj3)
        self.gridLayout.addWidget(self.horizontalWidget, 0, 0, 1, 1)
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.grpProjectorPositioning)
        self.dockNavigation.setWidget(self.grpSettings)
        DomeGUI.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockNavigation)

        self.retranslateUi(DomeGUI)
        QtCore.QObject.connect(self.chkShowProjectorImages, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.glWidget.setShowProjectorImages)
        QtCore.QObject.connect(self.chkEdgeBlending, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.glWidget.setEdgeBlending)
        QtCore.QObject.connect(self.boxDomeDiameter, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.glWidget.setDomeDiameter)
        QtCore.QObject.connect(self.boxBaseHeight, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.glWidget.setBaseHeight)
        QtCore.QObject.connect(self.boxTowerHeight, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.glWidget.setTowerHeight)
        QtCore.QObject.connect(self.chkShowDome, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.glWidget.setShowDome)
        QtCore.QObject.connect(self.boxAngleOfView, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.glWidget.setAngleOfView)
        QtCore.QObject.connect(self.boxAspectRatio, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.glWidget.setAspectRatio)
        QtCore.QObject.connect(self.chkShowProjectors, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.glWidget.setShowProjectors)
        QtCore.QObject.connect(self.chkShowScreenPoints, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.glWidget.setShowScreenPoints)
        QtCore.QObject.connect(self.chkProjectedPoints, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.glWidget.setShowProjectedPoints)
        QtCore.QObject.connect(self.btnProj1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.glWidget.setProj1)
        QtCore.QObject.connect(self.btnProj2, QtCore.SIGNAL(_fromUtf8("clicked()")), self.glWidget.setProj2)
        QtCore.QObject.connect(self.btnProj3, QtCore.SIGNAL(_fromUtf8("clicked()")), self.glWidget.setProj3)
        QtCore.QObject.connect(self.boxYawAngle, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.glWidget.setYawAngle)
        QtCore.QObject.connect(self.boxPitchAngle, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.glWidget.setPitchAngle)
        QtCore.QObject.connect(self.boxOffsetX, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.glWidget.setOffsetX)
        QtCore.QObject.connect(self.boxOffsetY, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.glWidget.setOffsetY)
        QtCore.QObject.connect(self.boxOffsetZ, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.glWidget.setOffsetZ)
        QtCore.QMetaObject.connectSlotsByName(DomeGUI)

    def retranslateUi(self, DomeGUI):
        DomeGUI.setWindowTitle(QtGui.QApplication.translate("DomeGUI", "Dome", None, QtGui.QApplication.UnicodeUTF8))
        self.dockNavigation.setWindowTitle(QtGui.QApplication.translate("DomeGUI", "Dome Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.grpGeneral.setTitle(QtGui.QApplication.translate("DomeGUI", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.chkShowProjectorImages.setText(QtGui.QApplication.translate("DomeGUI", "Show projector images", None, QtGui.QApplication.UnicodeUTF8))
        self.chkEdgeBlending.setText(QtGui.QApplication.translate("DomeGUI", "Enable Edge Blending", None, QtGui.QApplication.UnicodeUTF8))
        self.grpDome.setTitle(QtGui.QApplication.translate("DomeGUI", "Dome", None, QtGui.QApplication.UnicodeUTF8))
        self.lbDomeDiameter.setText(QtGui.QApplication.translate("DomeGUI", "Dome Diameter", None, QtGui.QApplication.UnicodeUTF8))
        self.lbBaseHeight.setText(QtGui.QApplication.translate("DomeGUI", "Base Height", None, QtGui.QApplication.UnicodeUTF8))
        self.lbTowerHeight.setText(QtGui.QApplication.translate("DomeGUI", "Tower Height", None, QtGui.QApplication.UnicodeUTF8))
        self.chkShowDome.setText(QtGui.QApplication.translate("DomeGUI", "Show dome", None, QtGui.QApplication.UnicodeUTF8))
        self.grpProjectorSettings.setTitle(QtGui.QApplication.translate("DomeGUI", "Projector Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.lbAngleOfView.setText(QtGui.QApplication.translate("DomeGUI", "Angle of View", None, QtGui.QApplication.UnicodeUTF8))
        self.lbAspectRatio.setText(QtGui.QApplication.translate("DomeGUI", "Aspect Ratio", None, QtGui.QApplication.UnicodeUTF8))
        self.chkShowProjectors.setText(QtGui.QApplication.translate("DomeGUI", "Show Projectors", None, QtGui.QApplication.UnicodeUTF8))
        self.chkShowScreenPoints.setText(QtGui.QApplication.translate("DomeGUI", "Show screen points", None, QtGui.QApplication.UnicodeUTF8))
        self.chkProjectedPoints.setText(QtGui.QApplication.translate("DomeGUI", "Show projected points", None, QtGui.QApplication.UnicodeUTF8))
        self.grpProjectorPositioning.setTitle(QtGui.QApplication.translate("DomeGUI", "Projector Positioning", None, QtGui.QApplication.UnicodeUTF8))
        self.lbOffset.setText(QtGui.QApplication.translate("DomeGUI", "Offset", None, QtGui.QApplication.UnicodeUTF8))
        self.lbPitchAngle.setText(QtGui.QApplication.translate("DomeGUI", "Pitch Angle", None, QtGui.QApplication.UnicodeUTF8))
        self.lbYawAngle.setText(QtGui.QApplication.translate("DomeGUI", "Yaw Angle", None, QtGui.QApplication.UnicodeUTF8))
        self.lbProjector.setText(QtGui.QApplication.translate("DomeGUI", "Projector", None, QtGui.QApplication.UnicodeUTF8))
        self.btnProj1.setText(QtGui.QApplication.translate("DomeGUI", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.btnProj2.setText(QtGui.QApplication.translate("DomeGUI", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.btnProj3.setText(QtGui.QApplication.translate("DomeGUI", "3", None, QtGui.QApplication.UnicodeUTF8))

from GLWidget import GLWidget
